// <auto-generated />
namespace PleasantEnglish.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241134073_BlogModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
